---
exclude: ^(subprojects|toolbox\/third-party)/
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:
# C source format; minor difference between .c / .h, much different style for the fio io-engine.
# For the details, then compare: toolbox/clang-format-*
- repo: local
  hooks:
  - id: clang-format
    name: C-format-headers
    language: system
    entry: toolbox/pcf_clang_format.py
    args: ["--style-file", "toolbox/clang-format-h"]
    files: \.h$

  - id: clang-format
    name: C-format-source
    language: system
    entry: toolbox/pcf_clang_format.py
    args: ["--style-file", "toolbox/clang-format-c"]
    files: \.c$
    exclude: xnvme_fioe.c$

# REUSE-software compliance check
- repo: https://github.com/fsfe/reuse-tool
  rev: v3.1.0a1
  hooks:
  - id: reuse

# Yaml: intended for the GitHUB Actions .yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml # pre-commit-hook-yamlfmt only works on valid YAML files
    name: YAML-format-check
    types: [file]
    files: \.(yaml|yml|config|workflow)$
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    name: YAML-format
    args:
    - '--mapping=2'
    - '--sequence=2'
    - '--offset=0'
    - '--width=120'
    - '--preserve-quotes'
    types: [file]
    files: \.(yaml|yml|config|workflow)$

# Python: for all the helpers in toolbox/*
- repo: https://github.com/psf/black
  rev: '24.4.2'
  hooks:
  - id: black
    name: Python-format-black
- repo: https://github.com/pycqa/isort
  rev: '5.13.2'
  hooks:
  # Available args: https://pycqa.github.io/isort/docs/configuration/options.html
  - id: isort
    name: Python-format-isort
    args:
    - '--profile=black'
    - '--line-length=88'
- repo: https://github.com/pycqa/flake8
  rev: '7.0.0'
  hooks:
  - id: flake8
    name: Python-lint-flake8
    args:
    - --extend-ignore=E203,F401,F811,E501
    exclude: (ctypes_mapping\/api\.py)$

# Rust tools
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
    name: Rust-fmt-xnvme
    args: ['--verbose', '--manifest-path', 'rust/xnvme/Cargo.toml', '--']

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
    name: Rust-fmt-xnvme-sys
    args: ['--verbose', '--manifest-path', 'rust/xnvme-sys/Cargo.toml', '--']
